const CompnyData = [
  {
    image: "URL_of_image_1",
    businessRepresentative: {
      name: "Company 001",
      role: "Role 1",
      email: "contact001@company.com",
      phone: "+919876543201",
      location: "City 1, State 1",
    },
    businessDetails: {
      industry: "Industry 1, Sector 1",
      businessDetails: "Details about Company 001",
      organizationWebsite: "www.company001.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 1,
  },
  {
    image: "URL_of_image_2",
    businessRepresentative: {
      name: "Company 002",
      role: "Role 2",
      email: "contact002@company.com",
      phone: "+919876543202",
      location: "City 2, State 2",
    },
    businessDetails: {
      industry: "Industry 2, Sector 2",
      businessDetails: "Details about Company 002",
      organizationWebsite: "www.company002.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 2,
  },
  {
    image: "URL_of_image_3",
    businessRepresentative: {
      name: "Company 003",
      role: "Role 3",
      email: "contact003@company.com",
      phone: "+919876543203",
      location: "City 3, State 3",
    },
    businessDetails: {
      industry: "Industry 3, Sector 3",
      businessDetails: "Details about Company 003",
      organizationWebsite: "www.company003.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "Openings Available",
    id: 3,
  },
  {
    image: "URL_of_image_4",
    businessRepresentative: {
      name: "Company 004",
      role: "Role 4",
      email: "contact004@company.com",
      phone: "+919876543204",
      location: "City 4, State 4",
    },
    businessDetails: {
      industry: "Industry 4, Sector 4",
      businessDetails: "Details about Company 004",
      organizationWebsite: "www.company004.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 4,
  },
  {
    image: "URL_of_image_5",
    businessRepresentative: {
      name: "Company 005",
      role: "Role 5",
      email: "contact005@company.com",
      phone: "+919876543205",
      location: "City 5, State 5",
    },
    businessDetails: {
      industry: "Industry 5, Sector 5",
      businessDetails: "Details about Company 005",
      organizationWebsite: "www.company005.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 5,
  },
  {
    image: "URL_of_image_6",
    businessRepresentative: {
      name: "Company 006",
      role: "Role 6",
      email: "contact006@company.com",
      phone: "+919876543206",
      location: "City 6, State 6",
    },
    businessDetails: {
      industry: "Industry 6, Sector 6",
      businessDetails: "Details about Company 006",
      organizationWebsite: "www.company006.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "Openings Available",
    id: 6,
  },
  {
    image: "URL_of_image_7",
    businessRepresentative: {
      name: "Company 007",
      role: "Role 7",
      email: "contact007@company.com",
      phone: "+919876543207",
      location: "City 7, State 7",
    },
    businessDetails: {
      industry: "Industry 7, Sector 7",
      businessDetails: "Details about Company 007",
      organizationWebsite: "www.company007.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 7,
  },
  {
    image: "URL_of_image_8",
    businessRepresentative: {
      name: "Company 008",
      role: "Role 8",
      email: "contact008@company.com",
      phone: "+919876543208",
      location: "City 8, State 8",
    },
    businessDetails: {
      industry: "Industry 8, Sector 8",
      businessDetails: "Details about Company 008",
      organizationWebsite: "www.company008.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 8,
  },
  {
    image: "URL_of_image_9",
    businessRepresentative: {
      name: "Company 009",
      role: "Role 9",
      email: "contact009@company.com",
      phone: "+919876543209",
      location: "City 9, State 9",
    },
    businessDetails: {
      industry: "Industry 9, Sector 9",
      businessDetails: "Details about Company 009",
      organizationWebsite: "www.company009.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "Openings Available",
    id: 9,
  },
  {
    image: "URL_of_image_10",
    businessRepresentative: {
      name: "Company 010",
      role: "Role 10",
      email: "contact010@company.com",
      phone: "+919876543210",
      location: "City 10, State 10",
    },
    businessDetails: {
      industry: "Industry 10, Sector 10",
      businessDetails: "Details about Company 010",
      organizationWebsite: "www.company010.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 10,
  },
  {
    image: "URL_of_image_11",
    businessRepresentative: {
      name: "Company 011",
      role: "Role 11",
      email: "contact011@company.com",
      phone: "+919876543211",
      location: "City 11, State 11",
    },
    businessDetails: {
      industry: "Industry 11, Sector 11",
      businessDetails: "Details about Company 011",
      organizationWebsite: "www.company011.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 11,
  },
  {
    image: "URL_of_image_12",
    businessRepresentative: {
      name: "Company 012",
      role: "Role 12",
      email: "contact012@company.com",
      phone: "+919876543212",
      location: "City 12, State 12",
    },
    businessDetails: {
      industry: "Industry 12, Sector 12",
      businessDetails: "Details about Company 012",
      organizationWebsite: "www.company012.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "Openings Available",
    id: 12,
  },
  {
    image: "URL_of_image_13",
    businessRepresentative: {
      name: "Company 013",
      role: "Role 13",
      email: "contact013@company.com",
      phone: "+919876543213",
      location: "City 13, State 13",
    },
    businessDetails: {
      industry: "Industry 13, Sector 13",
      businessDetails: "Details about Company 013",
      organizationWebsite: "www.company013.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 13,
  },
  {
    image: "URL_of_image_14",
    businessRepresentative: {
      name: "Company 014",
      role: "Role 14",
      email: "contact014@company.com",
      phone: "+919876543214",
      location: "City 14, State 14",
    },
    businessDetails: {
      industry: "Industry 14, Sector 14",
      businessDetails: "Details about Company 014",
      organizationWebsite: "www.company014.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 14,
  },
  {
    image: "URL_of_image_15",
    businessRepresentative: {
      name: "Company 015",
      role: "Role 15",
      email: "contact015@company.com",
      phone: "+919876543215",
      location: "City 15, State 15",
    },
    businessDetails: {
      industry: "Industry 15, Sector 15",
      businessDetails: "Details about Company 015",
      organizationWebsite: "www.company015.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "Openings Available",
    id: 15,
  },
  {
    image: "URL_of_image_16",
    businessRepresentative: {
      name: "Company 016",
      role: "Role 16",
      email: "contact016@company.com",
      phone: "+919876543216",
      location: "City 16, State 16",
    },
    businessDetails: {
      industry: "Industry 16, Sector 16",
      businessDetails: "Details about Company 016",
      organizationWebsite: "www.company016.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 16,
  },
  {
    image: "URL_of_image_17",
    businessRepresentative: {
      name: "Company 017",
      role: "Role 17",
      email: "contact017@company.com",
      phone: "+919876543217",
      location: "City 17, State 17",
    },
    businessDetails: {
      industry: "Industry 17, Sector 17",
      businessDetails: "Details about Company 017",
      organizationWebsite: "www.company017.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 17,
  },
  {
    image: "URL_of_image_18",
    businessRepresentative: {
      name: "Company 018",
      role: "Role 18",
      email: "contact018@company.com",
      phone: "+919876543218",
      location: "City 18, State 18",
    },
    businessDetails: {
      industry: "Industry 18, Sector 18",
      businessDetails: "Details about Company 018",
      organizationWebsite: "www.company018.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "Openings Available",
    id: 18,
  },
  {
    image: "URL_of_image_19",
    businessRepresentative: {
      name: "Company 019",
      role: "Role 19",
      email: "contact019@company.com",
      phone: "+919876543219",
      location: "City 19, State 19",
    },
    businessDetails: {
      industry: "Industry 19, Sector 19",
      businessDetails: "Details about Company 019",
      organizationWebsite: "www.company019.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 19,
  },
  {
    image: "URL_of_image_20",
    businessRepresentative: {
      name: "Company 020",
      role: "Role 20",
      email: "contact020@company.com",
      phone: "+919876543220",
      location: "City 20, State 20",
    },
    businessDetails: {
      industry: "Industry 20, Sector 20",
      businessDetails: "Details about Company 020",
      organizationWebsite: "www.company020.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 20,
  },
  {
    image: "URL_of_image_21",
    businessRepresentative: {
      name: "Company 021",
      role: "Role 21",
      email: "contact021@company.com",
      phone: "+919876543221",
      location: "City 21, State 21",
    },
    businessDetails: {
      industry: "Industry 21, Sector 21",
      businessDetails: "Details about Company 021",
      organizationWebsite: "www.company021.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "Openings Available",
    id: 21,
  },
  {
    image: "URL_of_image_22",
    businessRepresentative: {
      name: "Company 022",
      role: "Role 22",
      email: "contact022@company.com",
      phone: "+919876543222",
      location: "City 22, State 22",
    },
    businessDetails: {
      industry: "Industry 22, Sector 22",
      businessDetails: "Details about Company 022",
      organizationWebsite: "www.company022.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 22,
  },
  {
    image: "URL_of_image_23",
    businessRepresentative: {
      name: "Company 023",
      role: "Role 23",
      email: "contact023@company.com",
      phone: "+919876543223",
      location: "City 23, State 23",
    },
    businessDetails: {
      industry: "Industry 23, Sector 23",
      businessDetails: "Details about Company 023",
      organizationWebsite: "www.company023.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 23,
  },
  {
    image: "URL_of_image_24",
    businessRepresentative: {
      name: "Company 024",
      role: "Role 24",
      email: "contact024@company.com",
      phone: "+919876543224",
      location: "City 24, State 24",
    },
    businessDetails: {
      industry: "Industry 24, Sector 24",
      businessDetails: "Details about Company 024",
      organizationWebsite: "www.company024.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "Openings Available",
    id: 24,
  },
  {
    image: "URL_of_image_25",
    businessRepresentative: {
      name: "Company 025",
      role: "Role 25",
      email: "contact025@company.com",
      phone: "+919876543225",
      location: "City 25, State 25",
    },
    businessDetails: {
      industry: "Industry 25, Sector 25",
      businessDetails: "Details about Company 025",
      organizationWebsite: "www.company025.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 25,
  },
  {
    image: "URL_of_image_26",
    businessRepresentative: {
      name: "Company 026",
      role: "Role 26",
      email: "contact026@company.com",
      phone: "+919876543226",
      location: "City 26, State 26",
    },
    businessDetails: {
      industry: "Industry 26, Sector 26",
      businessDetails: "Details about Company 026",
      organizationWebsite: "www.company026.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 26,
  },
  {
    image: "URL_of_image_27",
    businessRepresentative: {
      name: "Company 027",
      role: "Role 27",
      email: "contact027@company.com",
      phone: "+919876543227",
      location: "City 27, State 27",
    },
    businessDetails: {
      industry: "Industry 27, Sector 27",
      businessDetails: "Details about Company 027",
      organizationWebsite: "www.company027.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "Openings Available",
    id: 27,
  },
  {
    image: "URL_of_image_28",
    businessRepresentative: {
      name: "Company 028",
      role: "Role 28",
      email: "contact028@company.com",
      phone: "+919876543228",
      location: "City 28, State 28",
    },
    businessDetails: {
      industry: "Industry 28, Sector 28",
      businessDetails: "Details about Company 028",
      organizationWebsite: "www.company028.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "No Data Available",
    id: 28,
  },
  {
    image: "URL_of_image_29",
    businessRepresentative: {
      name: "Company 029",
      role: "Role 29",
      email: "contact029@company.com",
      phone: "+919876543229",
      location: "City 29, State 29",
    },
    businessDetails: {
      industry: "Industry 29, Sector 29",
      businessDetails: "Details about Company 029",
      organizationWebsite: "www.company029.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India"],
    },
    currentOpenings: "No Data Available",
    id: 29,
  },
  {
    image: "URL_of_image_30",
    businessRepresentative: {
      name: "Company 030",
      role: "Role 30",
      email: "contact030@company.com",
      phone: "+919876543230",
      location: "City 30, State 30",
    },
    businessDetails: {
      industry: "Industry 30, Sector 30",
      businessDetails: "Details about Company 030",
      organizationWebsite: "www.company030.com",
    },
    recruitBasics: {
      candidateTypes: [
        "Graduate Interns",
        "Student Interns",
        "Graduate Full Time",
        "Graduate Part Time",
      ],
      locations: ["India", "USA", "UK"],
    },
    currentOpenings: "Openings Available",
    id: 30,
  },
];

export default CompnyData;
